// Accounts management codes
export const LOGIN_SUCCESS = 1000;
export const LOGIN_SUCCESS_WITH_FACEBOOK = 1001;
export const LOGIN_FAIL = 1005;
export const INVALID_TOKEN = 1006;
export const LOGIN_FAIL_WITH_FACEBOOK = 1007;
export const ACCOUNT_DISABLED = 1008;
export const CREATE_USER_SUCCESS = 1009;
export const USER_ALREDY_EXISTS = 1010;
export const CREATE_USER_FAILED = 1011;
export const ACCOUNT_ACTIVATED = 1012;
export const INVALID_CONFIRMATION_TOKEN = 1013;
export const PASSWORD_ALREDY_REQUEST = 1014;
export const PASSWORD_RESET_REQUEST_MADE = 1015;
export const NO_SUCH_USER_EXIST = 1016;
export const PASSWORD_SUCCESSFULLY_RESET = 1017;
